class Recipe {
  String name;
  String category;
  String description;
  String cookTime;
  String servings;
  String difficulty;
  String image;
  List<String> ingredients;
  List<String> steps;

  Recipe({
    required this.name,
    required this.category,
    required this.description,
    required this.cookTime,
    required this.servings,
    required this.difficulty,
    required this.image,
    required this.ingredients,
    required this.steps,
  });
}

var recipeList = [
  Recipe(
    name: 'Nasi Goreng Spesial',
    category: 'Main Course',
    description:
        'Nasi goreng khas Indonesia dengan telur, ayam, dan bumbu rempah pilihan.',
    cookTime: '20 menit',
    servings: '2',
    difficulty: 'Mudah',
    image: 'nasi_goreng_spesial.jpg',
    ingredients: [
      '2 piring nasi putih',
      '2 butir telur',
      '100 gr ayam suwir',
      '2 siung bawang putih',
      '2 sdm kecap manis',
      '1 sdm saus tiram',
      'Garam & merica secukupnya',
    ],
    steps: [
      'Panaskan minyak, tumis bawang putih hingga harum.',
      'Masukkan telur, orak-arik sebentar.',
      'Tambahkan ayam suwir, aduk rata.',
      'Masukkan nasi, tambahkan kecap dan saus tiram.',
      'Aduk rata hingga bumbu meresap.',
      'Angkat dan sajikan hangat.',
    ],
  ),
  Recipe(
    name: 'Sate Ayam Madura',
    category: 'Main Course',
    description:
        'Sate ayam khas Madura yang terkenal dengan bumbu kacangnya yang kental.',
    cookTime: '40 menit',
    servings: '4',
    difficulty: 'Menengah',
    image: 'sate_ayam_madura.jpeg',
    ingredients: [
      '500 gr daging ayam fillet',
      '10 tusuk sate',
      '2 sdm kecap manis',
      '1 sdm minyak goreng',
      '100 gr kacang tanah goreng',
      '2 siung bawang putih',
      'Cabai sesuai selera',
      'Air secukupnya',
    ],
    steps: [
      'Potong daging ayam kotak kecil, tusukkan ke tusuk sate.',
      'Haluskan kacang tanah, bawang, dan cabai.',
      'Tambahkan air dan kecap ke dalam bumbu, masak hingga mengental.',
      'Bakar sate hingga matang sambil diolesi bumbu.',
      'Sajikan dengan bumbu kacang di atasnya.',
    ],
  ),
  Recipe(
    name: 'Pisang Goreng Crispy',
    category: 'Snack',
    description: 'Pisang goreng renyah di luar, lembut di dalam.',
    cookTime: '15 menit',
    servings: '3',
    difficulty: 'Mudah',
    image: 'pisang_goreng_crispy.jpg',
    ingredients: [
      '5 buah pisang kepok',
      '100 gr tepung terigu',
      '50 gr tepung beras',
      '1 sdm gula',
      'Sejumput garam',
      'Air secukupnya',
      'Minyak goreng',
    ],
    steps: [
      'Campur tepung, gula, garam, dan air hingga adonan kental.',
      'Kupas dan belah pisang sesuai selera.',
      'Celupkan pisang ke dalam adonan.',
      'Goreng dalam minyak panas hingga kuning keemasan.',
      'Angkat dan tiriskan.',
    ],
  ),
  Recipe(
    name: 'Rendang Daging',
    category: 'Main Course',
    description:
        'Rendang daging sapi khas Minang yang dimasak lama hingga bumbu meresap dan kuah mengering.',
    cookTime: '3 jam',
    servings: '6',
    difficulty: 'Sulit',
    image: 'rendang_daging.png',
    ingredients: [
      '1 kg daging sapi',
      '400 ml santan kental',
      '10 siung bawang merah',
      '6 siung bawang putih',
      '5 cm jahe',
      '5 cm lengkuas',
      '5 daun jeruk',
      '2 batang serai',
      'Cabe merah, garam, gula',
    ],
    steps: [
      'Haluskan bumbu, tumis sampai harum.',
      'Tambahkan daging, aduk hingga berubah warna.',
      'Masukkan santan, daun jeruk, serai.',
      'Masak dengan api kecil hingga santan pecah dan mengering.',
      'Aduk sesekali agar matang merata.',
    ],
  ),
  Recipe(
    name: 'Soto Ayam',
    category: 'Soup',
    description: 'Soto ayam bening dengan kuah kuning dan rempah harum.',
    cookTime: '50 menit',
    servings: '4',
    difficulty: 'Menengah',
    image: 'soto_ayam.jpg',
    ingredients: [
      '500 gr ayam potong',
      '2 liter air',
      '4 siung bawang putih',
      '6 siung bawang merah',
      '2 cm kunyit',
      '2 batang serai',
      'Daun jeruk, garam, merica',
    ],
    steps: [
      'Rebus ayam hingga empuk.',
      'Haluskan bumbu, tumis hingga harum.',
      'Masukkan ke rebusan ayam.',
      'Tambahkan serai dan daun jeruk.',
      'Angkat, sajikan dengan pelengkap.',
    ],
  ),
  Recipe(
    name: 'Gado-Gado',
    category: 'Salad',
    description:
        'Salad sayuran dengan saus kacang dan pelengkap telur, tahu, dan tempe.',
    cookTime: '25 menit',
    servings: '3',
    difficulty: 'Mudah',
    image: 'gado_gado.jpg',
    ingredients: [
      '1 buah kentang rebus',
      '2 telur rebus',
      '100 gr taoge',
      '100 gr kol',
      '2 buah tahu goreng',
      '2 buah tempe goreng',
      'Bumbu kacang siap pakai',
    ],
    steps: [
      'Susun sayur, tahu, tempe di piring.',
      'Siram saus kacang.',
      'Taburi bawang goreng dan kerupuk.',
      'Sajikan.',
    ],
  ),
  Recipe(
    name: 'Bakso Kuah',
    category: 'Main Course',
    description:
        'Bakso sapi dengan kuah kaldunya yang gurih dan pelengkap mi serta sawi.',
    cookTime: '1 jam',
    servings: '4',
    difficulty: 'Menengah',
    image: 'bakso_kuah.jpg',
    ingredients: [
      '500 gr daging sapi giling',
      '100 gr tepung tapioka',
      '4 siung bawang putih',
      'Garam, merica',
      '2 liter kaldu sapi',
      'Mi dan sawi sebagai pelengkap',
    ],
    steps: [
      'Campur daging, tepung, bumbu, bentuk bulat.',
      'Rebus bakso hingga mengapung.',
      'Rebus mi dan sawi.',
      'Siapkan kuah, masukkan bakso.',
      'Tambahkan mi dan sawi.',
      'Sajikan hangat.',
    ],
  ),
  Recipe(
    name: 'Pecel Lele',
    category: 'Main Course',
    description: 'Lele goreng kriuk disajikan dengan sambal dan lalapan.',
    cookTime: '30 menit',
    servings: '2',
    difficulty: 'Mudah',
    image: 'pecel_lele.jpg',
    ingredients: [
      '2 ekor ikan lele',
      'Minyak goreng',
      'Sambal terasi',
      'Daun kemangi, kubis, mentimun',
    ],
    steps: [
      'Goreng lele hingga krispi.',
      'Siapkan sambal dan lalapan.',
      'Sajikan lele dengan sambal.',
    ],
  ),
  Recipe(
    name: 'Martabak Manis',
    category: 'Dessert',
    description:
        'Martabak manis tebal dan empuk dengan topping berbagai pilihan.',
    cookTime: '45 menit',
    servings: '4',
    difficulty: 'Menengah',
    image: 'martabak_manis.jpg',
    ingredients: [
      '200 gr tepung terigu',
      '2 sdt ragi instan',
      '1 sdm gula',
      '300 ml susu cair',
      'Telur, baking powder',
      'Mentega, topping meses',
    ],
    steps: [
      'Campur bahan, biarkan fermentasi.',
      'Tuang ke pan, tutup hingga muncul lubang.',
      'Oles mentega dan topping.',
      'Lipat dan potong-potong.',
    ],
  ),
  Recipe(
    name: 'Tumis Kangkung',
    category: 'Side Dish',
    description: 'Kangkung tumis pedas dengan bawang putih dan cabai.',
    cookTime: '10 menit',
    servings: '2',
    difficulty: 'Mudah',
    image: 'tumis_kangkung.jpg',
    ingredients: [
      '1 ikat kangkung',
      '3 siung bawang putih',
      '2 cabai merah',
      '1 sdm saus tiram',
      'Garam, minyak goreng',
    ],
    steps: [
      'Tumis bawang dan cabai hingga harum.',
      'Masukkan kangkung dan saus tiram.',
      'Aduk cepat, sajikan.',
    ],
  ),
  Recipe(
    name: 'Ikan Bakar',
    category: 'Main Course',
    description: 'Ikan bakar dengan bumbu rempah khas Indonesia.',
    cookTime: '35 menit',
    servings: '2',
    difficulty: 'Menengah',
    image: 'ikan_bakar.jpeg',
    ingredients: [
      '1 ekor ikan (gurame/kakap)',
      '3 sdm kecap manis',
      '2 siung bawang putih',
      '3 bawang merah',
      '1 cm jahe',
      'Garam, jeruk nipis',
    ],
    steps: [
      'Haluskan bumbu, lumuri ikan.',
      'Bakar ikan hingga matang.',
      'Sajikan dengan sambal.',
    ],
  ),
  Recipe(
    name: 'Sayur Asem',
    category: 'Soup',
    description:
        'Sayur asem segar dengan isian jagung, labu, dan kacang panjang.',
    cookTime: '30 menit',
    servings: '4',
    difficulty: 'Mudah',
    image: 'sayur_asem.jpg',
    ingredients: [
      '1 buah jagung manis',
      '100 gr labu siam',
      '50 gr kacang panjang',
      '2 liter air',
      'Bumbu sayur asem instan',
    ],
    steps: [
      'Rebus air hingga mendidih.',
      'Masukkan semua sayuran.',
      'Tambahkan bumbu instan.',
      'Masak hingga matang.',
    ],
  ),
  Recipe(
    name: 'Opor Ayam',
    category: 'Main Course',
    description: 'Opor ayam dengan kuah santan kuning yang gurih.',
    cookTime: '1 jam',
    servings: '5',
    difficulty: 'Menengah',
    image: 'opor_ayam.jpg',
    ingredients: [
      '1 ekor ayam',
      '500 ml santan',
      'Bumbu opor instan',
      '2 batang serai',
      '3 lembar daun salam',
    ],
    steps: [
      'Rebus ayam hingga empuk.',
      'Tumis bumbu instan.',
      'Masukkan ayam, santan, serai, dan daun salam.',
      'Masak hingga bumbu meresap.',
    ],
  ),
  Recipe(
    name: 'Gudeg',
    category: 'Main Course',
    description:
        'Gudeg nangka muda khas Yogyakarta dengan rasa manis dan gurih.',
    cookTime: '4 jam',
    servings: '6',
    difficulty: 'Sulit',
    image: 'gudeg.jpg',
    ingredients: [
      '500 gr nangka muda',
      '200 gr telur rebus',
      '1 liter santan',
      'Gula merah, garam',
      'Bumbu gudeg instan',
    ],
    steps: [
      'Rebus nangka muda hingga empuk.',
      'Masukkan santan, bumbu, gula, dan garam.',
      'Masak dengan api kecil hingga meresap.',
    ],
  ),
  Recipe(
    name: 'Rawon',
    category: 'Soup',
    description: 'Sup daging berkuah hitam khas Jawa Timur dari kluwek.',
    cookTime: '2 jam',
    servings: '4',
    difficulty: 'Menengah',
    image: 'rawon.jpg',
    ingredients: [
      '500 gr daging sapi',
      '4 buah kluwek',
      'Bumbu rawon instan',
      '2 liter air',
      'Taoge pendek sebagai pelengkap',
    ],
    steps: [
      'Rebus daging hingga empuk.',
      'Tumis bumbu instan dan kluwek.',
      'Masukkan ke dalam rebusan daging.',
      'Sajikan dengan taoge.',
    ],
  ),
  Recipe(
    name: 'Mi Goreng',
    category: 'Main Course',
    description: 'Mi goreng sederhana dengan sayuran dan telur.',
    cookTime: '20 menit',
    servings: '2',
    difficulty: 'Mudah',
    image: 'mi_goreng.jpg',
    ingredients: [
      '1 bungkus mi instan',
      '1 butir telur',
      'Sawi, kol secukupnya',
      '2 sdm kecap manis',
      'Bawang goreng',
    ],
    steps: [
      'Rebus mi, tiriskan.',
      'Tumis telur dan sayuran.',
      'Masukkan mi dan kecap.',
      'Aduk rata, sajikan dengan bawang goreng.',
    ],
  ),
  Recipe(
    name: 'Capcay',
    category: 'Side Dish',
    description: 'Tumis aneka sayuran dengan tambahan ayam atau seafood.',
    cookTime: '25 menit',
    servings: '3',
    difficulty: 'Mudah',
    image: 'capcay.jpg',
    ingredients: [
      '100 gr wortel',
      '100 gr kembang kol',
      '50 gr buncis',
      '100 gr ayam fillet',
      'Bumbu capcay instan',
    ],
    steps: [
      'Tumis ayam hingga matang.',
      'Masukkan sayuran, tumis sebentar.',
      'Tambahkan bumbu dan sedikit air.',
      'Masak hingga sayuran matang.',
    ],
  ),
  Recipe(
    name: 'Perkedel Kentang',
    category: 'Side Dish',
    description: 'Perkedel kentang lembut dengan campuran daging cincang.',
    cookTime: '30 menit',
    servings: '4',
    difficulty: 'Mudah',
    image: 'perkedel_kentang.png',
    ingredients: [
      '500 gr kentang',
      '100 gr daging cincang',
      '1 butir telur',
      'Bawang goreng, seledri',
      'Garam, merica',
    ],
    steps: [
      'Goreng kentang, haluskan.',
      'Campur dengan semua bahan.',
      'Bentuk bulat pipih.',
      'Goreng hingga keemasan.',
    ],
  ),
  Recipe(
    name: 'Ayam Goreng',
    category: 'Main Course',
    description: 'Ayam goreng renyah dengan bumbu ungkep khas.',
    cookTime: '50 menit',
    servings: '4',
    difficulty: 'Menengah',
    image: 'ayam_goreng.jpg',
    ingredients: ['1 ekor ayam', 'Bumbu ayam goreng instan', 'Minyak goreng'],
    steps: [
      'Ungkep ayam dengan bumbu.',
      'Goreng hingga matang dan renyah.',
      'Sajikan dengan sambal.',
    ],
  ),
  Recipe(
    name: 'Es Campur',
    category: 'Dessert',
    description: 'Es serut dengan aneka buah, jeli, dan sirup.',
    cookTime: '15 menit',
    servings: '2',
    difficulty: 'Mudah',
    image: 'es_campur.jpg',
    ingredients: [
      'Es serut secukupnya',
      'Aneka buah (alpukat, nangka)',
      'Jeli, cincau',
      'Susu kental manis, sirup cocopandan',
    ],
    steps: [
      'Tata isian di mangkuk.',
      'Tambahkan es serut.',
      'Siram dengan susu dan sirup.',
    ],
  ),
  Recipe(
    name: 'Singkong Goreng Keju',
    category: 'Snack',
    description:
        'Singkong goreng renyah di luar, empuk di dalam, disajikan dengan parutan keju.',
    cookTime: '25 menit',
    servings: '4',
    difficulty: 'Mudah',
    image: 'singkong_goreng_keju.png',
    ingredients: [
      '500 gr singkong',
      'Air secukupnya',
      'Garam, bawang putih',
      'Keju parut untuk topping',
      'Minyak goreng',
    ],
    steps: [
      'Kupas dan potong singkong, rebus dengan bawang dan garam.',
      'Tiriskan dan diamkan dalam freezer selama 1 jam.',
      'Goreng hingga keemasan.',
      'Taburi keju parut dan sajikan.',
    ],
  ),
  Recipe(
    name: 'Bakwan Jagung',
    category: 'Snack',
    description:
        'Bakwan jagung renyah dengan rasa gurih dan manis dari jagung.',
    cookTime: '30 menit',
    servings: '4',
    difficulty: 'Mudah',
    image: 'bakwan_jagung.jpg',
    ingredients: [
      '2 buah jagung manis',
      '100 gr tepung terigu',
      '1 batang daun bawang',
      '2 siung bawang putih',
      'Garam, merica, air secukupnya',
    ],
    steps: [
      'Serut jagung dan campur dengan bahan lainnya.',
      'Tambahkan air hingga adonan cukup kental.',
      'Goreng adonan sesendok demi sesendok hingga keemasan.',
      'Angkat dan sajikan.',
    ],
  ),
];